import raw from "@/data/industries.seed.json";
import rawEvidence from "@/data/evidence.seed.json";
import rawCells from "@/data/market-cells.seed.json";
import { evidenceSchema, industriesSchema, marketCellSchema } from "./schema";
import { calculateEEB, confidenceFromEvidence } from "./algorithm";
import { z } from "zod";
export const industries = industriesSchema.parse(raw).map((item) => ({ ...item, eeb: calculateEEB(item) }));
export type IndustryWithEEB = (typeof industries)[number];
export const categories = [...new Set(industries.map((x) => x.category))];
export const getIndustry = (id: string) => industries.find((x) => x.id === id);
export const evidence = z.array(evidenceSchema).parse(rawEvidence);
export const marketCells = z.array(marketCellSchema).parse(rawCells).map((cell) => ({...cell,eeb:calculateEEB(cell)}));
export const getIndustryEvidence = (industryId:string) => evidence.filter((x)=>x.industryId===industryId);
export const getIndustryCells = (industryId:string) => marketCells.filter((x)=>x.industryId===industryId);
export const getIndustryConfidence = (industryId:string) => confidenceFromEvidence(getIndustryEvidence(industryId).map((x)=>({grade:x.grade,directness:x.directness,generalizable:x.generalizable,ageYears:Math.max(0,2026-Number(x.publishedAt.slice(0,4)))})));
